let me see the changes
vanheeringen-lab/seq2science pull request #600
Opened 2020-12-07 14:25 UTC by Maarten-vd-Sande

**What problem is the PR solving / What's new?**
A description of the problem that is being solved, or which new feature is implemented. Please link to other relevant issues/pr if relevant

**What did change**
Explain clearly and concisely what you changed. Why did you take certain design decisions?

**Checklist**
- [x] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [ ] I updated the CHANGELOG
- [x] These changes are covered by the tests

2020-12-07 18:43 UTC, Maarten-vd-Sande commented
@siebrenf this is ready. Maybe we should keep this here a bit longer? We can release it maybe together with rerunning and scRNA? Or too much big changes at the same time, so if bugs appear we won't know what is causing it?

2020-12-09 13:17 UTC, siebrenf requested changes
scripts still need some attention. sec.

2020-12-09 13:17 UTC, siebrenf commented on seq2science/rules/peak_counts.smk
> +    Use gimmemotif's coverage_table to generate a count table with the nr of reads
🎉

2020-12-09 13:25 UTC, siebrenf approved these changes
I think that's it.

Yea, we should run a few more test runs with this. I'll rerun Angela's (RNA-seq & ATAC-seq) data to compare it! (she should have it ~ next week)

2020-12-09 13:59 UTC, Maarten-vd-Sande commented
thanks for the catches, I really though I had them all (those names are everywhere :yum: )

2021-01-26 20:26 UTC, merged