update kb-python
vanheeringen-lab/seq2science pull request #716
Opened 2021-06-03 11:00 UTC by Maarten-vd-Sande

**What problem is the PR solving / What's new?**
@tilschaef some updates to kb-python. Not sure if they break anything

**Checklist**
- [x] I made a PR to develop (not master)
- [ ] If applicable: I updated the docs
- [x] I updated the CHANGELOG
- [ ] These changes are covered by the tests

2021-06-15 11:19 UTC, tilschaef commented
@Maarten-vd-Sande , apparently this version has been "yanked" and should not be installed (https://github.com/pachterlab/kb_python/releases/tag/v0.26.1). There is now v0.26.3.

2021-06-15 11:20 UTC, tilschaef requested changes
We should consider upgrading to v0.26.3 instead

2021-06-15 13:34 UTC, Maarten-vd-Sande commented
YANKED!
![yank](https://user-images.githubusercontent.com/15323399/122061401-c373f880-cdee-11eb-90d7-429a14531f9c.gif)

@tilschaef can I ask you to test this? There are some important changes, e..g.:

> Deprecated --lamanno and --nucleus flags. Use --workflow instead
> Whitelists are now provided by the ngs-tools library.

2021-06-28 12:38 UTC, tilschaef approved these changes

2021-07-06 15:50 UTC, merged